package com.rokid.cxrmsamples.dataBeans

enum class UsageType {
    USAGE_TYPE_AUDIO,
    USAGE_TYPE_VIDEO,
    USAGE_TYPE_PHOTO,
    USAGE_TYPE_FILE,
    USAGE_TYPE_AI,
    USAGE_CUSTOM_VIEW,
    USAGE_TYPE_CUSTOM_PROTOCOL,
    USAGE_TYPE_TELEPROMPTER,
    USAGE_TYPE_TRANSLATION,
    USAGE_TYPE_DEVICE_INFORMATION,
}